package ro.ecoregistru;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Structural checks on the waste code nomenclator seed (the European List of Waste,
 * Decision 2014/955/EU) that Flyway loads into waste_codes.
 *
 * The list is regenerated by scripts/generate_waste_codes.py, which validates the same
 * rules at generation time; they are repeated here so a hand-edited or half-downloaded
 * CSV fails the build instead of reaching a customer's evidence sheet. The chapter/
 * subchapter headings the generator writes as comments carry the structure of the
 * official list, which is what makes the placement checks possible from the CSV alone.
 *
 * Fingerprint source: docs/surse-oficiale.md, section 3.1.
 */
class WasteCodeSeedTest {

    private static final String CSV_PATH = "/seed/waste_codes.csv";

    private static final int EXPECTED_TOTAL = 842;
    private static final int EXPECTED_HAZARDOUS = 408;
    private static final Map<String, Integer> EXPECTED_PER_CHAPTER = Map.ofEntries(
            Map.entry("01", 24), Map.entry("02", 38), Map.entry("03", 19), Map.entry("04", 21),
            Map.entry("05", 24), Map.entry("06", 48), Map.entry("07", 78), Map.entry("08", 38),
            Map.entry("09", 13), Map.entry("10", 173), Map.entry("11", 27), Map.entry("12", 23),
            Map.entry("13", 34), Map.entry("14", 5), Map.entry("15", 12), Map.entry("16", 72),
            Map.entry("17", 38), Map.entry("18", 16), Map.entry("19", 99), Map.entry("20", 40));

    private static final Pattern CODE_FORMAT = Pattern.compile("\\d{2} \\d{2} \\d{2}");
    private static final Pattern CHAPTER_HEADING = Pattern.compile("# == (\\d{2}) .+");
    private static final Pattern SUBCHAPTER_HEADING = Pattern.compile("# -- (\\d{2} \\d{2}) .+");

    /** A seed line, together with the headings it was listed under. */
    private record SeededCode(String code, String name, boolean hazardous, String chapter, String subchapter) {
    }

    private static List<SeededCode> codes;

    @BeforeAll
    static void loadSeed() throws Exception {
        codes = new ArrayList<>();
        try (InputStream in = WasteCodeSeedTest.class.getResourceAsStream(CSV_PATH)) {
            assertThat(in).as("seed file on the classpath: %s", CSV_PATH).isNotNull();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String chapter = null;
                String subchapter = null;
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.trim();
                    if (trimmed.isEmpty()) {
                        continue;
                    }
                    var chapterMatch = CHAPTER_HEADING.matcher(trimmed);
                    var subchapterMatch = SUBCHAPTER_HEADING.matcher(trimmed);
                    if (chapterMatch.matches()) {
                        chapter = chapterMatch.group(1);
                        subchapter = null;
                    } else if (subchapterMatch.matches()) {
                        subchapter = subchapterMatch.group(1);
                    } else if (!trimmed.startsWith("#")) {
                        // Same split as V4__reseed_waste_codes: official names contain commas.
                        int firstComma = trimmed.indexOf(',');
                        int lastComma = trimmed.lastIndexOf(',');
                        assertThat(firstComma).as("first comma in seed line: %s", trimmed).isGreaterThan(0);
                        assertThat(lastComma).as("second comma in seed line: %s", trimmed).isGreaterThan(firstComma);
                        codes.add(new SeededCode(
                                trimmed.substring(0, firstComma),
                                trimmed.substring(firstComma + 1, lastComma),
                                Boolean.parseBoolean(trimmed.substring(lastComma + 1)),
                                chapter,
                                subchapter));
                    }
                }
            }
        }
    }

    @Test
    void everyCodeIsUnique() {
        assertThat(codes).extracting(SeededCode::code).doesNotHaveDuplicates();
    }

    @Test
    void everyCodeHasSixDigitsAndANonEmptyName() {
        assertThat(codes).allSatisfy(entry -> {
            assertThat(entry.code()).matches(CODE_FORMAT);
            assertThat(entry.name()).isNotBlank();
            assertThat(entry.name()).isEqualTo(entry.name().trim());
        });
    }

    @Test
    void everyCodeSitsUnderTheSubchapterItsDigitsClaim() {
        assertThat(codes).allSatisfy(entry ->
                assertThat(entry.subchapter())
                        .as("subchapter heading above code %s", entry.code())
                        .isEqualTo(entry.code().substring(0, 5)));
    }

    @Test
    void everyCodeSitsUnderTheChapterItsDigitsClaim() {
        assertThat(codes).allSatisfy(entry ->
                assertThat(entry.chapter())
                        .as("chapter heading above code %s", entry.code())
                        .isEqualTo(entry.code().substring(0, 2)));
    }

    @Test
    void chapterDistributionMatchesTheOfficialList() {
        Map<String, Integer> perChapter = new LinkedHashMap<>();
        codes.forEach(entry -> perChapter.merge(entry.code().substring(0, 2), 1, Integer::sum));

        assertThat(perChapter).containsExactlyInAnyOrderEntriesOf(EXPECTED_PER_CHAPTER);
        assertThat(codes).hasSize(EXPECTED_TOTAL);
        assertThat(codes.stream().filter(SeededCode::hazardous)).hasSize(EXPECTED_HAZARDOUS);
    }
}
