/**
 * Central Romanian UI strings. Keep all user-facing text here so it can be
 * extracted into an i18n framework later without hunting through components.
 */
export const strings = {
  appName: "EcoRegistru",
  tagline: "Evidența și raportarea gestiunii deșeurilor",

  header: {
    // Shown above the nav: the current company. For PLATFORM_ADMIN it's a tenant switcher.
    currentCompany: "Firma curentă",
    selectCompany: "Alege firma",
    noCompanySelected: "Nicio firmă selectată",
    platformAdmin: "Administrator platformă",
    loadCompaniesError: "Nu am putut încărca firmele.",
  },

  nav: {
    dashboard: "Panou",
    movements: "Mișcări",
    evidences: "Evidențe",
    partners: "Parteneri",
    deadlines: "Termene",
    auditFile: "Dosar de control",
    clients: "Clienți",
    settings: "Setări",
    logout: "Deconectare",
  },

  login: {
    title: "Autentificare",
    email: "Email",
    password: "Parolă",
    submit: "Intră în cont",
    loading: "Se autentifică...",
    forgotPassword: "Ai uitat parola?",
    genericError: "Autentificare eșuată. Verifică datele și încearcă din nou.",
  },

  dashboard: {
    title: "Panou de control",
    welcome: "Bine ai venit",
    addMovement: "Adaugă mișcare",
    // stat tiles
    statMovements: "Mișcări luna aceasta",
    statMovementsSub: "înregistrări în {month}",
    statDeadlines: "Termene de făcut",
    statDeadlinesSub: "din care {overdue} depășite",
    statExpiring: "Autorizații care expiră",
    statExpiringSub: "parteneri cu autorizația aproape expirată",
    // sections
    upcomingTitle: "Termene următoare",
    upcomingEmpty: "Niciun termen deschis pentru anul curent.",
    expiringTitle: "Autorizații care expiră curând",
    expiringEmpty: "Nicio autorizație de partener aproape de expirare.",
    viewAll: "Vezi toate",
    loadError: "Nu am putut încărca datele panoului.",
  },

  movements: {
    title: "Mișcări de deșeuri",
    subtitle: "Intrările și ieșirile de deșeuri, pe puncte de lucru și luni.",
    add: "Adaugă mișcare",
    addTitle: "Adaugă mișcare",
    editTitle: "Editează mișcarea",
    empty: "Nicio mișcare pentru filtrele alese.",
    loadError: "Nu am putut încărca mișcările.",
    // filters
    filterMonth: "Luna",
    filterWorkPoint: "Punct de lucru",
    filterWasteCode: "Cod deșeu",
    filterAll: "Toate",
    allMonths: "Toate lunile",
    clearFilters: "Șterge filtrele",
    // columns
    colDate: "Data",
    colWasteCode: "Cod deșeu",
    colOperation: "Operațiune",
    colQuantity: "Cantitate",
    colPartner: "Operator",
    colInternalGenerator: "Secția",
    colWorkPoint: "Punct de lucru",
    colDocument: "Document",
    colAttachments: "Atașamente",
    // form fields
    date: "Data",
    wasteCode: "Cod deșeu",
    wasteCodePlaceholder: "Alege un cod de deșeu",
    wasteCodeSearch: "Caută după cod sau denumire…",
    quantity: "Cantitate",
    unit: "Unitate",
    weighedAtUnloading: "Se cântărește la descărcare",
    weighedAtUnloadingHint:
      "Bifează dacă nu ai cântar și cantitatea o stabilește destinatarul la descărcare. Mișcarea se salvează fără cantitate, iar formularul de transport se tipărește cu rubrica goală — se completează pe loc, după cântărire.",
    awaitingWeighing: "De cântărit",
    awaitingWeighingHint:
      "Deșeul a plecat, dar cantitatea nu e încă știută. Completeaz-o când primești cântarul de la destinatar.",
    volumeM3: "Volum (mc)",
    volumeM3Hint: "Singura măsură pe care o ai fără cântar. Nu ține loc de kilograme în Anexa 1.",
    operation: "Operațiune",
    physicalState: "Stare fizică",
    physicalStatePlaceholder: "— fără —",
    storageAndTreatment: "Stocare și tratare (cap. 2)",
    storageType: "Stocare — tipul",
    treatmentMethod: "Tratare — ce se face",
    nomenclatorPlaceholder: "— fără —",
    operationCode: "Cod operațiune (R/D)",
    operationCodeHint:
      "Fișa Anexa 1 nu are coloană de „predare”: cantitatea se raportează la „valorificată” (cod R) sau la „eliminată final” (cod D). Predarea se înregistrează alegând operațiunea și partenerul care o face.",
    partner: "Operatorul care efectuează operațiunea",
    partnerPlaceholder: "— noi, pe amplasamentul propriu —",
    partnerHint:
      "Lasă gol dacă operațiunea o faci tu. Dacă predai deșeul, alege partenerul: el e „agentul economic care efectuează operația” din cap. 3 / cap. 4.",
    internalGenerator: "Generator intern (Secția)",
    internalGeneratorPlaceholder: "— fără —",
    internalGeneratorHint: "Sursa din punctul de lucru. Se tipărește în coloana „Secția” din cap. 2.",
    documentReference: "Referință document",
    documentReferencePlaceholder: "ex. aviz / factură",
    notes: "Note",
    attachments: "Atașamente",
    hazardous: "Periculos",
    // Anexa 3 — dovada predării
    anexa3Section: "Anexa 3 — dovada predării",
    anexa3SectionHint:
      "Formularul de încărcare-descărcare deșeuri nepericuloase (HG 1061/2008), tipărit din această mișcare. Completează ce apare pe hârtie.",
    anexa3Download: "Anexa 3",
    anexa3Downloading: "Se generează...",
    anexa3Error: "Formularul nu a putut fi generat.",
    unloadDate: "Data descărcării",
    transportPartner: "Transportator",
    transportPartnerPlaceholder: "— transportăm noi —",
    driverName: "Delegat (șofer)",
    driverIdentification: "Act de identitate",
    driverIdentificationPlaceholder: "ex. serie și nr. CI",
    vehicleRegistration: "Nr. înmatriculare",
    transportDestinations: "Destinat:",
    transportDestinationsHint: "Se pot bifa mai multe, ca pe formular.",
    // validation / feedback
    weighingNeedsPartner: "Cântărirea la descărcare o face destinatarul: alege partenerul care preia deșeul.",
    recoveryCodeRequired: "Alege un cod de valorificare (R) pentru valorificare.",
    disposalCodeRequired: "Alege un cod de eliminare (D) pentru eliminare.",
    legacyExitHint:
      "Linie veche, fără cod R/D: cantitatea a ieșit de pe amplasament, dar nu intră în nicio coloană oficială. Alege valorificare sau eliminare și codul operațiunii ca să o completezi.",
    created: "Mișcare adăugată.",
    updated: "Mișcare actualizată.",
    deleted: "Mișcare ștearsă.",
    saveError: "Salvarea a eșuat. Verifică datele și încearcă din nou.",
    confirmDelete: "Sigur ștergi această mișcare?",
    attachmentError: "Fișierul nu a putut fi încărcat.",
    attachmentDeleted: "Atașament șters.",
    noWorkPointHint: "Adaugă întâi un punct de lucru din Setări.",
  },

  settings: {
    title: "Setări",
    workPoints: {
      title: "Puncte de lucru",
      subtitle: "Locațiile pentru care ții evidența deșeurilor.",
      add: "Adaugă punct de lucru",
      edit: "Editează punctul de lucru",
      name: "Denumire",
      address: "Adresă",
      empty: "Niciun punct de lucru încă.",
      active: "Activ",
      inactive: "Inactiv",
      deactivate: "Dezactivează",
      confirmDeactivate: "Sigur dezactivezi acest punct de lucru?",
      created: "Punct de lucru adăugat.",
      updated: "Punct de lucru actualizat.",
      deactivated: "Punct de lucru dezactivat.",
      saveError: "Salvarea a eșuat. Încearcă din nou.",
      loadError: "Nu am putut încărca punctele de lucru.",
    },
    internalGenerators: {
      title: "Generatori interni",
      subtitle:
        "Sursele din interiorul punctelor de lucru — birouri, producție, cantină. Se tipăresc în coloana „Secția” din cap. 2 al Anexei 1.",
      add: "Adaugă generator intern",
      addTitle: "Adaugă generator intern",
      editTitle: "Editează generatorul intern",
      workPoint: "Punct de lucru",
      workPointLocked: "Punctul de lucru nu se poate schimba. Dezactivează-l aici și adaugă-l acolo.",
      name: "Denumire (Secția)",
      namePlaceholder: "ex. birouri, producție, cantină",
      description: "Descriere",
      empty: "Niciun generator intern încă.",
      active: "Activ",
      inactive: "Inactiv",
      deactivate: "Dezactivează",
      confirmDeactivate: "Sigur dezactivezi acest generator intern?",
      created: "Generator intern adăugat.",
      updated: "Generator intern actualizat.",
      deactivated: "Generator intern dezactivat.",
      saveError: "Salvarea a eșuat. Încearcă din nou.",
      loadError: "Nu am putut încărca generatorii interni.",
      noWorkPoints: "Adaugă întâi un punct de lucru.",
    },
  },

  partners: {
    title: "Parteneri",
    subtitle:
      "Firmele cu care lucrezi: clienții (le predai deșeu și le facturezi) și furnizorii (îți prestează serviciul și îți facturează).",
    add: "Adaugă partener",
    addTitle: "Adaugă partener",
    editTitle: "Editează partenerul",
    empty: "Niciun partener încă.",
    loadError: "Nu am putut încărca partenerii.",
    // columns
    name: "Denumire",
    cui: "CUI",
    type: "Tip",
    authorizationNumber: "Nr. autorizație",
    authorizationExpiry: "Expirare autorizație",
    role: "Rol comercial",
    filterRole: "Rol",
    filterRoleAll: "Toate rolurile",
    roleRequired: "Alege cel puțin un rol: client, furnizor sau ambele.",
    address: "Adresa sediului social",
    workPointAddress: "Adresa punctului de lucru",
    workPointAddressHint:
      "Unde se descarcă efectiv deșeul, dacă e altundeva decât sediul. Asta se tipărește pe Anexa 3.",
    tradeRegisterNumber: "Nr. Registrul Comerțului",
    tradeRegisterNumberPlaceholder: "ex. J12/1351/2011",
    transportLicenseNumber: "Licență de transport mărfuri",
    transportLicenseExpiry: "Expiră licența",
    anexa3Hint:
      "Datele astea se tipăresc pe Anexa 3 când îi predai deșeu sau când el face transportul.",
    // form placeholders
    cuiPlaceholder: "ex. RO12345678",
    authorizationNumberPlaceholder: "ex. 123/2024",
    typePlaceholder: "Alege tipul",
    // status / badges
    active: "Activ",
    inactive: "Inactiv",
    noAuthorization: "—",
    expired: "Expirată",
    expiringSoon: "Expiră curând",
    deactivate: "Dezactivează",
    confirmDeactivate: "Sigur dezactivezi acest partener? Acțiunea nu poate fi anulată.",
    // feedback
    created: "Partener adăugat.",
    updated: "Partener actualizat.",
    deactivated: "Partener dezactivat.",
    saveError: "Salvarea a eșuat. Verifică datele și încearcă din nou.",
  },

  evidences: {
    title: "Evidența gestiunii deșeurilor",
    subtitle:
      "Situația lunară pe puncte de lucru și coduri de deșeu, cu stoc cumulativ. Regenerată din mișcări.",
    regenerate: "Regenerează",
    regenerating: "Se regenerează...",
    loadError: "Nu am putut încărca evidența.",
    regenerateError: "Regenerarea a eșuat. Încearcă din nou.",
    regenerated: "Evidență regenerată: {count} linii pentru {year}.",
    // export
    export: "Export",
    exportExcel: "Export Excel",
    exportPdf: "Export PDF",
    exportError: "Exportul a eșuat. Încearcă din nou.",
    // filters
    filterYear: "An",
    filterMonth: "Luna",
    filterWorkPoint: "Punct de lucru",
    allMonths: "Toate lunile",
    allWorkPoints: "Toate",
    // columns — Anexa 1, cap. 1: "Generate | din care: valorificată | eliminată final |
    // rămasă în stoc". Fișa nu are coloană de predare, deci predarea apare în „Valorificat" sau
    // „Eliminat", după codul R/D al operațiunii făcute de destinatar.
    colWorkPoint: "Punct de lucru",
    colMonth: "Luna",
    colWasteCode: "Cod deșeu",
    colGenerated: "Generat",
    colRecovered: "Valorificat",
    colDisposed: "Eliminat",
    colHandedOver: "din care predat",
    colUnclassified: "Neclasificat",
    colStock: "Stoc",
    hazardous: "Periculos",
    // line warnings
    // Cele două vederi ale tabului. Implicit e registrul de predări, cerut la meeting; vederea
    // lunară rămâne fiindcă poartă stocul cumulativ, singura cifră pe care ochiul n-o reface și
    // exact ce cere fișa Anexa 1.
    viewHandovers: "Predări",
    viewMonthly: "Anexa 1 — lunar",
    handoversSubtitle:
      "Ce a plecat de pe amplasament: cantitatea, data predării, cine a primit și sub ce cod. Din rândul de aici tipărești Anexa 3.",
    colHandoverDate: "Data predării",
    colOperationCode: "Operațiune",
    colPartnerName: "Partener",
    emptyHandovers: "Nicio predare pentru filtrele alese.",
    handoversLoadError: "Nu am putut încărca predările.",
    ownSite: "pe amplasament propriu",
    incomplete: "Incomplet",
    incompleteHint:
      "Cantitate ieșită fără cod de operațiune (R/D). Se scade din stoc, dar nu poate fi raportată în „Valorificat” sau „Eliminat” până nu completezi codul pe mișcare.",
    awaitingWeighing: "De cântărit",
    awaitingWeighingHint:
      "O ieșire din luna asta așteaptă cântarul destinatarului, deci totalurile sunt provizorii.",
    resaleSuspected: "De verificat",
    resaleSuspectedHint:
      "La acest punct de lucru și cod există și deșeu preluat de la terți. Dacă predarea dă mai departe marfă preluată, ea nu aparține Anexei 1, ci registrului cronologic (art. 48).",
    regeneratedCascade: "Evidență regenerată: {count} linii pentru {year} (și anii {years}).",
    // empty state
    empty: "Nu există linii de evidență pentru {year}.",
    emptyHint: "Apasă „Regenerează” pentru a calcula evidența anului {year} din mișcări.",
    // note about the cache being manually regenerated
    staleNote:
      "Evidența nu se actualizează singură. După ce adaugi sau ștergi mișcări, apasă „Regenerează”.",
  },

  deadlines: {
    title: "Termene de raportare",
    subtitle:
      "Calendarul obligațiilor de raportare pe firmă: SIM anual și, pentru firmele cu obligație, AFM lunar.",
    generate: "Generează termenele",
    generating: "Se generează...",
    generated: "Termene generate: {count} noi pentru {year}.",
    generateError: "Generarea termenelor a eșuat. Încearcă din nou.",
    loadError: "Nu am putut încărca termenele.",
    // filters
    filterYear: "An",
    // columns
    colReportType: "Raportare",
    colDueDate: "Termen",
    colStatus: "Status",
    colNote: "Notă",
    // actions
    markDone: "Marchează finalizat",
    reopen: "Redeschide",
    completed: "Termen marcat ca finalizat.",
    reopened: "Termen redeschis.",
    actionError: "Acțiunea a eșuat. Încearcă din nou.",
    // complete dialog
    completeTitle: "Marchează termenul ca finalizat",
    noteLabel: "Notă (opțional)",
    notePlaceholder: "ex. depus la ANPM pe 12.03, nr. înregistrare 1234",
    // empty state
    empty: "Niciun termen pentru {year}.",
    emptyHint: "Apasă „Generează termenele” pentru a crea calendarul anului {year}.",
  },

  auditFile: {
    title: "Dosar de control",
    subtitle:
      "Descarcă într-o singură arhivă tot ce ai nevoie la un control: evidența, autorizațiile partenerilor și documentele atașate.",
    filterYear: "An",
    download: "Descarcă dosarul (.zip)",
    downloading: "Se pregătește arhiva...",
    downloadError: "Descărcarea dosarului a eșuat. Încearcă din nou.",
    contents: "Arhiva conține:",
    contentEvidence: "Evidența gestiunii deșeurilor (Excel + PDF)",
    contentPartners: "Rezumat PDF cu autorizațiile partenerilor și statusul lor",
    contentAttachments: "Documentele justificative atașate mișcărilor (+ index)",
    note: "Notă: dosarul NU înlocuiește formularele oficiale (Anexa 1 / SIM / AFM); e un pachet de lucru pentru pregătirea controlului.",
  },

  clients: {
    title: "Clienți",
    subtitle:
      "Firmele pentru care ții evidența. Creezi firme și inviți utilizatori care primesc pe email un link de setare a parolei.",
    add: "Adaugă firmă",
    addTitle: "Adaugă firmă",
    editTitle: "Editează firma",
    empty: "Nicio firmă încă.",
    loadError: "Nu am putut încărca firmele.",
    onlyPlatformAdmin: "Această secțiune este disponibilă doar administratorului platformei.",
    // columns
    name: "Denumire",
    cui: "CUI",
    type: "Tip",
    afm: "Obligație AFM",
    // form fields
    namePlaceholder: "ex. Demo Reciclare SRL",
    cuiPlaceholder: "ex. RO12345678",
    afmLabel: "Firma are obligație de declarație AFM lunară",
    environmentalAuthNumber: "Nr. autorizație de mediu",
    environmentalAuthExpiry: "Expirare autorizație de mediu",
    address: "Adresă",
    contactName: "Persoană de contact",
    contactEmail: "Email de contact",
    contactPhone: "Telefon de contact",
    anexa3Series: "Serie formulare Anexa 3",
    anexa3SeriesPlaceholder: "ex. HMB",
    anexa3SeriesHint: "Apare pe formularele de transport; numărul îl alocăm noi, crescător.",
    // status / badges
    active: "Activ",
    inactive: "Inactiv",
    afmYes: "Da",
    afmNo: "Nu",
    // feedback
    created: "Firmă adăugată.",
    updated: "Firmă actualizată.",
    saveError: "Salvarea a eșuat. Verifică datele și încearcă din nou.",
    // invite user
    invite: "Invită utilizator",
    inviteTitle: "Invită utilizator în firma {company}",
    inviteEmail: "Email",
    inviteEmailPlaceholder: "utilizator@firma.ro",
    inviteRole: "Rol",
    inviteFirstName: "Prenume",
    inviteLastName: "Nume",
    inviteSubmit: "Trimite invitația",
    invited:
      "Utilizator invitat. I-am trimis (dacă emailul e configurat) un link de setare a parolei.",
    inviteError: "Invitația a eșuat. Verifică datele și încearcă din nou.",
    inviteHint:
      "Utilizatorul primește un email cu link de setare a parolei. Contul devine activ după ce își setează parola.",
  },

  // Romanian month names (index 0 = January), for display of the `month` field.
  months: [
    "Ianuarie",
    "Februarie",
    "Martie",
    "Aprilie",
    "Mai",
    "Iunie",
    "Iulie",
    "August",
    "Septembrie",
    "Octombrie",
    "Noiembrie",
    "Decembrie",
  ],

  // Romanian labels for backend enums (constants are English by convention).
  enums: {
    wasteOperation: {
      GENERATED: "Generare",
      COLLECTED: "Preluare de la terți",
      RECOVERED: "Valorificare",
      DISPOSED: "Eliminare",
      UNCLASSIFIED_OUT: "Ieșire neclasificată",
    },
    // The commercial role of a partner, as agreed on 23.08.2026.
    partnerRole: {
      client: "Client",
      clientHint: "Îi predai deșeu și îi facturezi tu.",
      supplier: "Furnizor",
      supplierHint: "Îți prestează serviciul și îți facturează el.",
      both: "Client + furnizor",
      none: "Rol nestabilit",
      noneHint: "Alege rolul la editare — nu îl putem deduce din datele existente.",
    },
    wasteRegister: {
      ANEXA_1: "Anexa 1 — deșeu propriu",
      ART_48: "Registru cronologic — preluat de la terți",
    },
    // HG 856/2002, anexa nr. 1, cap. 2, nota 3. Nota definește și „E — în vederea eliminării”,
    // dar niciun formular completat pe care îl avem nu îl scrie: pe fișele de eliminare coloana
    // rămâne goală, iar ce identifică eliminarea e codul D din cap. 4.
    treatmentPurpose: {
      V: "V — pentru valorificare",
    },
    // HG 856/2002, anexa nr. 1, cap. 2, nota 1 — tipul de stocare.
    storageType: {
      RM: "RM — Recipient metalic",
      RP: "RP — Recipient de plastic",
      BZ: "BZ — Bazin decantor",
      CT: "CT — Container transportabil",
      CF: "CF — Container fix",
      S: "S — Saci",
      PD: "PD — Platformă de deshidratare",
      VN: "VN — În vrac, neacoperit",
      VA: "VA — În vrac, incintă acoperită",
      RL: "RL — Recipient din lemn",
      A: "A — Altele",
    },
    // HG 856/2002, anexa nr. 1, cap. 2, nota 2 — modul de tratare. „D” e deshidratare, nu un cod
    // de eliminare: coliziunea de abreviere e a formularului, iar cele două sunt coloane diferite.
    treatmentMethod: {
      TM: "TM — Tratare mecanică",
      TC: "TC — Tratare chimică",
      TMC: "TMC — Tratare mecano-chimică",
      TB: "TB — Tratare biochimică",
      TT: "TT — Tratare termică",
      D: "D — Deshidratare",
      A: "A — Altele",
    },
    // Anexa 3 la HG 1061/2008, caseta „Destinat:”. Se pot bifa mai multe.
    transportDestination: {
      COLECTARE: "Colectării",
      STOCARE_TEMPORARA: "Stocării temporare",
      TRATARE: "Tratării",
      VALORIFICARE: "Valorificării",
      ELIMINARE: "Eliminării",
    },
    physicalState: {
      SOLID: "Solid",
      LIQUID: "Lichid",
      SLUDGE: "Nămol",
      PASTY: "Păstos",
      POWDER: "Pulbere",
      GASEOUS: "Gazos",
    },
    unit: {
      KG: "kg",
      TONS: "tone",
    },
    // Ce este partenerul in raport cu deseul. Transportatorul nu mai e o categorie: e o rubrica a
    // transportului, pe miscare.
    partnerType: {
      GENERATOR: "Generator",
      COLLECTOR: "Colector",
    },
    companyType: {
      GENERATOR: "Generator",
      COLLECTOR: "Colector",
      BOTH: "Generator și colector",
    },
    inviteRole: {
      ADMIN: "Administrator",
      OPERATOR: "Operator",
      CLIENT_VIEWER: "Vizualizare (read-only)",
    },
    reportType: {
      SIM_ANNUAL: "SIM (anual) — ANPM",
      AFM_MONTHLY: "AFM (lunar) — Fondul pentru Mediu",
      OTHER: "Altă raportare",
    },
    deadlineStatus: {
      UPCOMING: "De făcut",
      DONE: "Finalizat",
      OVERDUE: "Depășit",
    },
    // R/D recovery & disposal operation codes (Waste Framework Directive annexes).
    wasteOperationCode: {
      R1: "R1 — Combustibil sau altă sursă de energie",
      R2: "R2 — Recuperarea/regenerarea solvenților",
      R3: "R3 — Reciclarea substanțelor organice (non-solvenți)",
      R4: "R4 — Reciclarea metalelor și compușilor metalici",
      R5: "R5 — Reciclarea altor materiale anorganice",
      R6: "R6 — Regenerarea acizilor sau a bazelor",
      R7: "R7 — Recuperarea componentelor pentru reducerea poluării",
      R8: "R8 — Recuperarea componentelor din catalizatori",
      R9: "R9 — Rerafinarea sau alte reutilizări ale petrolului",
      R10: "R10 — Împrăștiere pe sol (beneficii agricole/ecologice)",
      R11: "R11 — Utilizarea deșeurilor din operațiunile R1–R10",
      R12: "R12 — Schimb de deșeuri pentru operațiunile R1–R11",
      R13: "R13 — Stocare înaintea operațiunilor R1–R12",
      D1: "D1 — Depozitare în sau pe sol",
      D2: "D2 — Tratarea solului",
      D3: "D3 — Injectare în adâncime",
      D4: "D4 — Acumulare la suprafață (iazuri, lagune)",
      D5: "D5 — Depozite special construite",
      D6: "D6 — Evacuare în ape (cu excepția mărilor)",
      D7: "D7 — Evacuare în mări/oceane",
      D8: "D8 — Tratament biologic",
      D9: "D9 — Tratament fizico-chimic",
      D10: "D10 — Incinerare pe sol",
      D11: "D11 — Incinerare pe mare",
      D12: "D12 — Depozitare permanentă",
      D13: "D13 — Amestecare înaintea operațiunilor D1–D12",
      D14: "D14 — Reambalare înaintea operațiunilor D1–D13",
      D15: "D15 — Stocare înaintea operațiunilor D1–D14",
    },
  },

  accountRequest: {
    // Public page
    title: "Cerere de cont EcoRegistru",
    subtitle:
      "Conturile se creează de echipa EcoRegistru, pe baza acestui formular. Completează-l o dată — din răspunsuri configurăm aplicația pentru tipul tău de activitate, ca să vezi doar ce îți trebuie.",
    sectionCompany: "Firma",
    sectionWorkPoint: "Punctul de lucru",
    sectionContact: "Persoana de contact",
    sectionAuthorization: "Autorizația de mediu",
    sectionTransport: "Transport",
    sectionWaste: "Deșeurile",
    companyName: "Denumirea firmei",
    cui: "CUI",
    cuiPlaceholder: "ex. RO12345678",
    companyType: "Ce faceți cu deșeurile",
    companyAddress: "Adresa sediului social",
    workPointName: "Denumirea punctului de lucru",
    workPointNamePlaceholder: "ex. Punct de lucru Cluj",
    workPointAddress: "Adresa punctului de lucru",
    workPointHint:
      "Locul unde se produce efectiv deșeul. Evidența se ține pe punct de lucru, nu pe firmă, iar adresa e des alta decât sediul social.",
    contactName: "Nume și prenume",
    contactEmail: "Email",
    contactPhone: "Telefon",
    contactHint: "Pe acest email primești datele de acces, după ce creăm contul.",
    environmentalAuthNumber: "Nr. autorizație de mediu",
    environmentalAuthExpiry: "Expiră la",
    transportMeans: "Cu ce transportați",
    transportMeansPlaceholder: "ex. autoutilitară 3,5 t, container 20 mc",
    transportLicenseNumber: "Licență de transport mărfuri",
    transportLicenseExpiry: "Expiră licența",
    transportHint: "Se completează doar dacă preluați deșeuri de la terți.",
    operationCodes: "Ce se întâmplă cu deșeul",
    operationCodesHint:
      "Bifează operațiunile pe care le folosiți. Doar acestea vor apărea în aplicație — poți lăsa necompletat dacă nu știi.",
    recovery: "Valorificare (R)",
    disposal: "Eliminare (D)",
    wasteCodesText: "Ce deșeuri generați / preluați",
    wasteCodesTextPlaceholder: "ex. carton, folie de plastic, deșeu menajer, moloz",
    wasteCodesTextHint:
      "Scrie-le în cuvintele tale. Le transformăm noi în codurile din Lista Europeană a Deșeurilor.",
    notes: "Alte observații",
    submit: "Trimite cererea",
    submitting: "Se trimite...",
    successTitle: "Cererea a fost trimisă",
    successBody:
      "Echipa EcoRegistru o verifică și îți creează contul. Primești datele de acces pe emailul completat.",
    submitError: "Trimiterea a eșuat. Verifică datele și încearcă din nou.",
    backToLogin: "Înapoi la autentificare",
    linkFromLogin: "Nu ai cont? Trimite o cerere",
    // Admin list
    adminTitle: "Cereri de cont",
    adminSubtitle: "Formularele trimise de clienți. Din ele se creează firmele.",
    adminEmpty: "Nicio cerere.",
    adminLoadError: "Nu am putut încărca cererile.",
    colCompany: "Firma",
    colType: "Tip",
    colContact: "Contact",
    colWaste: "Deșeuri",
    colDate: "Trimisă",
    colStatus: "Stare",
    approve: "Creează contul",
    reject: "Respinge",
    rejectPrompt: "De ce respingi cererea?",
    approved: "Firma a fost creată din cerere. Invită acum utilizatorul.",
    rejected: "Cerere respinsă.",
    actionError: "Acțiunea a eșuat. Încearcă din nou.",
    status: {
      NEW: "Nouă",
      APPROVED: "Cont creat",
      REJECTED: "Respinsă",
    },
  },

  companyProfile: {
    title: "Profilul firmei",
    subtitle:
      "Răspunsurile din formularul completat de client. Din ele se decide ce vede omul în aplicație — dacă nu completezi nimic, se oferă tot.",
    operationCodes: "Operațiuni de valorificare / eliminare",
    operationCodesHint:
      "Ce se întâmplă cu deșeul. Doar acestea apar la mișcări, după operațiune.",
    recovery: "Valorificare (R)",
    disposal: "Eliminare (D)",
    selectAll: "Toate",
    clearAll: "Niciuna",
    wasteCodes: "Coduri de deșeu din autorizație",
    wasteCodesHint:
      "Ce generează sau ce transportă. Din 842 de coduri rămân la vedere doar acestea.",
    addWasteCode: "Adaugă cod",
    removeWasteCode: "Scoate codul",
    transport: "Transport (doar pentru colectori)",
    transportMeans: "Cu ce transportă",
    transportMeansPlaceholder: "ex. autoutilitară 3,5 t, container 20 mc",
    transportLicenseNumber: "Licență de transport mărfuri",
    transportLicenseExpiry: "Expiră licența de transport",
    empty: "Necompletat — se oferă tot.",
  },

  common: {
    loading: "Se încarcă...",
    saving: "Se salvează...",
    save: "Salvează",
    cancel: "Anulează",
    delete: "Șterge",
    edit: "Editează",
    add: "Adaugă",
    close: "Închide",
    status: "Status",
    actions: "Acțiuni",
    requiredField: "Câmp obligatoriu.",
  },
} as const;
